### ISSUE TITLE
TimestampBehavior Expression conflict

### ISSUE THREAD

**Issue by antonkomarev** [Borales/yii2-elasticsearch-behavior#1]
If you are using TimestampBehavior with default settings:

```
[
    'class' => TimestampBehavior::className(),
    'createdAtAttribute' => 'created_at',
    'updatedAtAttribute' => 'updated_at',
    'value' => new Expression('NOW()'),
],
```

And current behavior with this config:

```
[
    'class' => '\borales\behaviors\elasticsearch\Behavior',
    'mode' => 'command',
    'elasticIndex' => 'project-index',
    'elasticType' => 'post',
    'dataMap' => [
        'id' => 'id',
        'title' => 'title',
        'body' => function () {
            return strip_tags($this->body);
        },
        'author' => function () {
            return $this->author->username;
        },
        'created_at' => function () {
            return $this->created_at;
        },
    ]
],
```

You will have an error from ElasticSearch on create

> "created_at":{"expression":"NOW()","params":[]}
> [error] => MapperParsingException[failed to parse [created_at]]; nested: ElasticsearchIllegalArgumentException[unknown property [expression]]; 

Same issue was in Yii1 behavior https://github.com/codemix/YiiElasticSearch/issues/23

**Comment by Borales** [comment]
@a-komarev thanks for a bug report. I've made a quick fix, hope it will cover this problem.

**Comment by antonkomarev** [comment]
@Borales this fix isn't working. `created_at` & `updated_at` fields are going inside of `is_callable($attribute)` statement.

**Comment by Borales** [comment]
@a-komarev can you show your `dataMap` value?

**Comment by antonkomarev** [comment]
This function is working for me. But code is heavy to read.

``` php
protected function getProcessedData()
{
    $data = [];
    foreach ($this->dataMap as $elasticField => $attribute) {
        if (is_callable($attribute)) {
            $calledFunction = call_user_func($attribute);
            if ($calledFunction instanceof Expression) {
                if (trim($calledFunction->expression) == 'NOW()') {
                    $data[$elasticField] = date("Y-m-d H:i:s");
                } else {
                    throw new InvalidParamException('Attribute "' . $elasticField . '" can not be instance of \yii\db\Expression');
                }
            } else {
                $data[$elasticField] = $calledFunction;
            }
        } else {
            $data[$elasticField] = $this->owner->{$attribute};
        }
    }
    return $data;
}
```

Attribute isn't instance of Expression while it isn't being called. Hope this helps.

**Comment by Borales** [comment]
@a-komarev ah, right! It's my mistake.
Hope the last commit will fix it.

**Comment by antonkomarev** [comment]
@Borales It's working now! Thanks for a quick fix.

**Comment by Borales** [comment]
@a-komarev thank you for your bug report!
I will add tests for these types.

**Comment by DeepikaSudheer** [comment]
How to resolve this error:
Setting unknown property: common\models\User::created_at timestamp

The below code is not working for me
[
    'class' => TimestampBehavior::className(),
    'createdAtAttribute' => 'created_at',
    'updatedAtAttribute' => 'updated_at',
    'value' => new Expression('NOW()'),
],
