### ISSUE TITLE
How to implement completion suggest

### ISSUE THREAD

**Issue by unglevan** [Borales/yii2-elasticsearch-behavior#5]
How i can implement completion suggestion?

**Comment by Borales** [comment]
@unglevan the purpose of this behavior is to help to auto-index documents to ElasticSearch.
For "suggestion" functionality - you should refer to the official Yii2 Documentation (and its extension) and ElasticSearch docs.

**Comment by unglevan** [comment]
@Borales Sr if i misunderstood. But in this docs.
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-suggesters-completion.html
We need add "suggest" as a "properties" that have to define in "dataMap" config right?
